/* exported loadFlavorTexts */

function loadFlavorTexts() {
	return {
		corridors:[
			"Un pasillo corto y seco.",
			"Las rocas crujen al caminar.",
			"Pisas algo fangoso.",
			"Oscuridad total.",
			"Inscripciones ilegible,s en las paredes.",
			"El viento aúlla en el estrecho pasadizo.",
			"Velas en lo largo de las paredes.",
			"Tu imagen se refleja en miles de cristales en la pared.",
			"Marcas de garras en paredes y suelo.",
			"Necesitas salir rápido de aquí.",
			"Oyes una puerta cerrarse.",
			"Oyes el eco de tus pasos por toda la mazmorra.",
			"Manchas de tinta bajan por las escaleras.",
			"Hay briznas de hierba entre los azulejos del suelo.",
			"Una puerta de madera se cierra detrás de ti.",
			"Cristales entintados en negro repartidos por el oscuro pasillo.",
			"La oscuridad te hace dudar de tu existencia.",
			"Gotas de agua de estalactitas.",
			"Una baba verde cubre las paredes.",
			"El techo está tan bajo que debes gatear.",
			"Túnel de tierra a punto de colapsar.",
			"Puertas de piedra rotas, usadas para bloquear a los intrusos.",
			"Hogar de cientos de murciélagos.",
			"Huele a madera quemada.",
		],
		rooms:[
			"Una luz tenue filtra entre las cortinas.",
			"Un enorme candelabro ilumina la habitación.",
			"El suelo está tan limpio que refleja tu imagen.",
			"Hay algunas cabezas colgando del techo.",
			"Gran estatua en forma de cubo en el centro.",
			"Sombras largas proyectadas por cuatro columnas.",
			"Amplio anfiteatro de mármol.",
			"Oyes susurros.",
			"Manchas frescas de sangre en el suelo.",
			"Sientes un olor insoportable.",
			"Paredes de oro.",
			"Te sientes fatigado, no es una buena señal.",
			"Esquivas un dardo disparado desde una estatua.",
			"Sientes que tu garganta se seca.",
			"Entras en una bodega con una luz tenue de antorchas.",
			"Fuego púrpura en un ábside en ruinas.",
			"Ves unas huellas de barro que llegan hasta el altar.",
			"Brillo tenue de armas en la armería.",
			"Un zumbido misterioso llena la cueva, atravesándote el cerebro.",
			"Un taller repleto de glifos y máquinas extrañas.",
			"Ves un cuchillo oxidado clavado en un cadáver putrefacto de un jabalí.",
			"Ves unos dibujos de criaturas y trampas en las paredes.",
			"Llegas a un patio soleado que calma tu espíritu.",
			"De la habitación romboide salen unos fluidos negros y espesos.",
			"Te encuentras en medio de un laberinto de espejos. ¿Dónde está la salida?",
			"Ves en una bóveda un montón de huesos en los rincones, junto a pacíficas estatuas.",
			"Te sorprende un estanque casi seco en la cueva, con luminiscencias de color verde mar.",
			"Algo en la habitación se te hace muy familiar... sientes un escalofrío.",
			"Un montón de hojas enormes de roble están apiladas en el suelo de la sala.",
			"Entras en una habitación cerrada que huele a muerte.",
			"Cada ángulo de la habitación está redondeado con hueso, ¿habrán sido los sabuesos?",
			"Un arroyo sale por una grieta.",
			"Esto parece un tablero de ajedrez gigante.",
			"Los ecos sugieren que esta habitación es más grande.",
			"En tu boca sientes un sabor a... ¿fresa?",
			"Ves un cielo nocturno con constelaciones desconocidas.",
			"Te topas con muebles enormes que te hacen sentir pequeño.",
			"Oyes un extraño zumbido en el suelo.",
		]
	};
}
